[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
dependsOn = ['setup']
cmds = [
    'composer install --no-dev --optimize-autoloader --ignore-platform-reqs'
]

[phases.build]
dependsOn = ['install']
cmds = [
    'php artisan key:generate --force',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
