[phases.setup]
nixPkgs = ['nodejs_20', 'php82', 'php82Packages.composer']

[phases.install]
dependsOn = ['setup']
cmds = [
    'composer install --no-dev --optimize-autoloader --ignore-platform-reqs',
    'export NODE_OPTIONS="--max-old-space-size=1024" && npm ci --no-audit --no-fund --maxsockets 1'
]

[phases.build]
dependsOn = ['install']
cmds = [
    'php artisan key:generate --force',
    'php artisan migrate --force',
    'export NODE_OPTIONS="--max-old-space-size=1024" && npm run build',
    'rm -rf node_modules'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
